DROP TABLE IF EXISTS cats, dollhouses;

CREATE TABLE cats (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  weight TEXT,
  age INTEGER NOT NULL
);

CREATE TABLE dollhouses (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  scale TEXT NOT NULL,
  price INTEGER NOT NULL
)