DROP TABLE IF EXISTS cats, dollhouses, books, paintings, games;

CREATE TABLE cats (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  weight TEXT,
  age INTEGER NOT NULL
);

CREATE TABLE dollhouses (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  scale TEXT NOT NULL,
  price INTEGER NOT NULL
);

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  year INTEGER NOT NULL
);

CREATE TABLE paintings (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  museum TEXT NOT NULL,
  artist TEXT NOT NULL
);

CREATE TABLE games (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  studio TEXT NOT NULL,
  rating INTEGER NOT NULL
)